const videos = [
{part:'Part 2',category:'Shifting',title:'Wide Build → Shift and Cover',file:'assets/videos/part2-01-wide-build-shift-and-cover.mp4',sequence:'Milan builds down the flank and moves possession toward Inter’s defensive third.',doneWell:'The ball-side center back moves toward the threat while the middle and far-side center backs slide across and protect the central corridor.',improve:'The far-side center back should begin squeezing while the pass is travelling, not after the receiver controls it.',cue:'Pressure • Cover • Balance'},
{part:'Part 2',category:'Box Defending',title:'Sustained Pressure → Box Compactness',file:'assets/videos/part2-02-sustained-pressure-box-compactness.mp4',sequence:'Milan keeps the ball around the edge of the box and changes the point of attack.',doneWell:'Inter repeatedly adjusts spacing and becomes narrower as the ball gets closer to goal.',improve:'Keep shrinking the horizontal gaps and identify near, central and far-post threats before the cross arrives.',cue:'Closer to goal = tighter back three'},
{part:'Part 2',category:'Shifting',title:'Midfield Progression → Back 3 Shift',file:'assets/videos/part2-03-midfield-progression-back3-shift.mp4',sequence:'Milan advances through midfield and moves Inter’s block laterally.',doneWell:'The back three retreats and shifts behind the midfield as a connected unit.',improve:'If one defender steps, the other two must already be narrowing and providing depth behind him.',cue:'Move as one line'},
{part:'Part 2',category:'Cross Defending',title:'Final Third Shift → Cross Defending',file:'assets/videos/part2-04-final-third-shift-cross-defending.mp4',sequence:'Milan circulates outside the box, shifts Inter, then attacks a crossing area.',doneWell:'Inter squeezes toward the ball side and defenders away from the ball move toward central danger.',improve:'The far defender must get fully goal-side of the far-post threat instead of guarding empty width.',cue:'Get across when the cross is coming'},
{part:'Part 2',category:'Learning Moment',title:'Goal Sequence — What Could Improve',file:'assets/videos/part2-05-goal-sequence-what-could-improve.mp4',sequence:'Milan progresses quickly through Inter’s defensive block and creates a central scoring chance.',doneWell:'Inter gets numbers back and tries to recover centrally.',improve:'One defender must affect the ball sooner while the second covers the inside lane and the third balances toward goal and the next runner.',cue:'Pressure • Cover • Balance'},

{part:'Part 3',category:'Compactness',title:'Milan Build → Inter Compact Press',file:'assets/videos/part3-01-milan-build-inter-compact-press.mp4',sequence:'Milan builds from the back while Inter controls central access.',doneWell:'The center backs hold their spacing behind the press instead of following players too far forward.',improve:'Do not let one center back jump out and leave a large channel behind him.',cue:'Stay connected behind the press'},
{part:'Part 3',category:'Shifting',title:'Progression → Narrow and Delay',file:'assets/videos/part3-02-milan-progression-inter-narrow-and-delay.mp4',sequence:'Milan advances through the middle-right area and Inter compresses space toward the ball.',doneWell:'The unit narrows and protects the central lane.',improve:'The far center back should start squeezing before the receiver turns forward.',cue:'Move while the pass travels'},
{part:'Part 3',category:'Cross Defending',title:'Cross → Defend Central Space',file:'assets/videos/part3-03-box-cross-inter-defend-central-space.mp4',sequence:'Milan delivers into the box and Inter has to protect runners close to goal.',doneWell:'The defenders collapse toward the six-yard and central corridor and prioritize the most dangerous runners.',improve:'Stay goal-side and communicate near, center and far-post responsibility earlier.',cue:'Defend danger, not fixed positions'},
{part:'Part 3',category:'Recovery',title:'Wide Attack → Recover Into Box',file:'assets/videos/part3-04-wide-attack-inter-recover-into-box.mp4',sequence:'Milan drives down the side and attacks the penalty area.',doneWell:'The ball-side defender engages while the other center backs recover toward goal and central runners.',improve:'The two covering center backs must squeeze across immediately when the outside defender is engaged.',cue:'One engages, two squeeze'},

{part:'Part 4',category:'Shifting',title:'Early Wide Attack → Shift',file:'assets/videos/part4-01-early-wide-attack-shift.mp4',sequence:'Milan progresses quickly toward the wide/half-space channel.',doneWell:'Inter retreats and shifts toward the ball side while the near defender deals with the immediate threat.',improve:'The far-side center back must travel with the play and not stay attached to his original side.',cue:'Ball moves → back three moves'},
{part:'Part 4',category:'Cross Defending',title:'Cross → Box Recovery',file:'assets/videos/part4-02-cross-and-box-recovery.mp4',sequence:'Milan gets the ball into a crossing and box-danger situation.',doneWell:'Inter collapses toward goal and prioritizes central runners and dangerous space.',improve:'Once the cross is likely, assign near-post, central and far-post danger immediately.',cue:'Protect runners before grass'},
{part:'Part 4',category:'Recovery',title:'Direct Attack → Back 3 Recovery',file:'assets/videos/part4-03-direct-attack-back3-recovery.mp4',sequence:'Milan drives directly at Inter from midfield.',doneWell:'The center backs drop together and protect the inside channel.',improve:'The first defender should engage only once the other two have established cover behind him.',cue:'Recover inside first'},
{part:'Part 4',category:'Compactness',title:'Final Third Shift → Box Compactness',file:'assets/videos/part4-04-final-third-shift-and-box-compactness.mp4',sequence:'Milan works the ball around Inter’s final third.',doneWell:'Inter narrows and reduces the spaces between the three center backs as the attack approaches goal.',improve:'Keep forcing the attack around the block rather than allowing a pass through the center.',cue:'Protect the middle first'},

{part:'Part 5',category:'Shifting',title:'Wide-Side Shift → Box Compactness',file:'assets/videos/part5-p5-01-wide-side-shift-and-box-compactness.mp4',sequence:'Milan attacks wide and forces Inter to move toward the ball side.',doneWell:'The ball-side defender engages, the central defender covers and the far center back squeezes toward goal.',improve:'The far-side defender can move earlier while the pass is still travelling.',cue:'Pressure • Cover • Balance'},
{part:'Part 5',category:'Compactness',title:'Milan Attack → Narrow and Cover',file:'assets/videos/part5-p5-02-milan-attack-inter-narrow-and-cover.mp4',sequence:'Milan sustains pressure around Inter’s defensive third.',doneWell:'Inter keeps small horizontal gaps and protects the inside first.',improve:'Avoid getting dragged to the touchline unless there is clear cover behind the defender who steps.',cue:'Inside first'},
{part:'Part 5',category:'Recovery',title:'Transition → Defend and Recover',file:'assets/videos/part5-p5-03-transition-defending-and-recovery.mp4',sequence:'Milan advances and Inter has to recover quickly into shape.',doneWell:'The recovery runs are toward goal and inside before the line expands again.',improve:'Only one defender should engage while the other two restore cover and balance.',cue:'Narrow first, expand later'},

{part:'Part 6',category:'Recovery',featured:true,title:'Featured — Transition Drop & Box Collapse',file:'assets/videos/part6-featured-transition-drop-box-collapse.mp4',sequence:'Milan attacks quickly and Inter’s defenders have to retreat into the box.',doneWell:'The back line drops centrally and protects the goal before trying to step again.',improve:'Communication must identify who takes the ball carrier and who protects the next runner.',cue:'Goal-side first'},
{part:'Part 6',category:'Compactness',title:'Build-Up Defense → Back 3 Spacing',file:'assets/videos/part6-p6-01-build-up-defense-and-back3-spacing.mp4',sequence:'Milan has possession in Inter’s half while pressure happens in front of the back three.',doneWell:'The three center backs hold depth and remain connected behind midfield pressure.',improve:'The far center back should keep checking the opposite runner while staying connected to the central center back.',cue:'Stay connected behind pressure'},
{part:'Part 6',category:'Recovery',title:'Emergency Recovery vs Direct Attack',file:'assets/videos/part6-p6-02-emergency-recovery-vs-direct-attack.mp4',sequence:'Milan attacks directly into space and Inter retreats toward its box.',doneWell:'Inter protects the central route and delays while recovering numbers.',improve:'Do not have multiple center backs step to the same attacker; one delays while the others protect goal and runners.',cue:'Do not double-step'},

{part:'Part 7',category:'Cross Defending',featured:true,title:'Featured — Wide Attack & Box Collapse',file:'assets/videos/part7-featured-wide-attack-box-collapse.mp4',sequence:'Milan attacks wide and Inter collapses toward the box as the threat develops.',doneWell:'The defenders away from the ball recover into central and far-post danger.',improve:'The far center back should get fully across before the cross is delivered.',cue:'Far CB: squeeze all the way across'},
{part:'Part 7',category:'Cross Defending',title:'Wide Attack → Cross Defending',file:'assets/videos/part7-p7-01-wide-attack-and-cross-defending.mp4',sequence:'Milan attacks the side of Inter’s box and looks to deliver across goal.',doneWell:'Inter collapses toward the cross and protects central and far-post spaces.',improve:'The far center back cannot remain attached to empty space on the opposite side.',cue:'Get across'},
{part:'Part 7',category:'Recovery',title:'Transition Drop → Inside Protection',file:'assets/videos/part7-p7-02-transition-drop-and-inside-protection.mp4',sequence:'Milan breaks forward and Inter’s defenders retreat together.',doneWell:'The defenders recover centrally and rebuild the line before stepping again.',improve:'Call early who takes the ball carrier and who provides cover.',cue:'Recover, organize, then step'},
{part:'Part 7',category:'Shifting',title:'Milan Progression → Back 3 Drop',file:'assets/videos/part7-p7-03-milan-progression-and-back3-drop.mp4',sequence:'Milan progresses through the middle/right channel as Inter drops.',doneWell:'The back three protects the middle while pressure comes from midfield and the wingback.',improve:'Do not break the line too early; force play around the block rather than through it.',cue:'Protect the center'},

{part:'Part 8',category:'Shifting',featured:true,title:'Featured — Shift to Right Flank',file:'assets/videos/part8-featured-shift-right-flank.mp4',sequence:'The ball moves toward Milan’s right-side attack and Inter’s defensive line travels with it.',doneWell:'The back three moves laterally rather than leaving the far-side center back disconnected.',improve:'The far center back can begin moving sooner so the line arrives compact before the next pass.',cue:'Shift on the pass'},
{part:'Part 8',category:'Box Defending',featured:true,title:'Featured — Cross & Compact Box',file:'assets/videos/part8-featured-cross-box-compact.mp4',sequence:'Milan reaches crossing territory and Inter has to defend the box.',doneWell:'Inter compresses the central area and protects runners close to goal.',improve:'The defenders should identify near, central and far-post threats even earlier.',cue:'Compact before the cross arrives'},
{part:'Part 8',category:'Recovery',featured:true,title:'Featured — Transition Recovery',file:'assets/videos/part8-featured-transition-recovery.mp4',sequence:'Inter loses control and has to recover toward its own goal.',doneWell:'The line narrows first and restores central protection before expanding.',improve:'The first defender should delay the ball carrier while the other two establish cover behind him.',cue:'Narrow first'},
{part:'Part 8',category:'Cross Defending',featured:true,title:'Featured — Wide Attack → Shift → Cross',file:'assets/videos/part8-featured-wide-shift-cross.mp4',sequence:'Milan attacks wide, Inter shifts, and the sequence develops into a cross.',doneWell:'The movement shows the complete chain: shift toward the ball, cover behind the first defender, squeeze centrally, then defend the cross.',improve:'The far center back should constantly check the far-post runner while squeezing across.',cue:'Shift → Cover → Squeeze → Defend'},
{part:'Part 8',category:'Shifting',title:'Final Third Attack → Inter Shift',file:'assets/videos/part8-p8-01-milan-final-third-attack-inter-shift.mp4',sequence:'Milan has sustained possession near Inter’s box and changes the angle of attack.',doneWell:'The back line moves together and keeps the box compact as the ball moves.',improve:'Start the lateral movement as the pass travels so the receiver does not face forward into an open lane.',cue:'Move early'},
{part:'Part 8',category:'Wide Defending',title:'Right-Side Attack → Box Protection',file:'assets/videos/part8-p8-02-right-side-attack-and-box-protection.mp4',sequence:'Milan attacks the right side with runners inside.',doneWell:'The ball-side center back manages the channel while the other two protect the middle and far side.',improve:'If the wingback is beaten, the outside center back should delay while the other two squeeze behind him.',cue:'Delay outside, protect inside'}
];

const grid=document.getElementById('videoGrid');
const filterRow=document.getElementById('filterRow');
const menuBtn=document.getElementById('menuBtn');
const siteNav=document.getElementById('siteNav');
menuBtn?.addEventListener('click',()=>siteNav.classList.toggle('open'));
siteNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>siteNav.classList.remove('open')));

const categories=['All',...new Set(videos.map(v=>v.category))];
const parts=['All Parts',...new Set(videos.map(v=>v.part))];
let activeCategory='All',activePart='All Parts';

function renderFilters(){
  filterRow.innerHTML=`<div class="filter-group"><span class="filter-label">Pattern</span>${categories.map((c,i)=>`<button class="filter-btn ${i===0?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="filter-group"><span class="filter-label">Match segment</span>${parts.map((p,i)=>`<button class="part-btn ${i===0?'active':''}" data-part="${p}">${p}</button>`).join('')}</div>`;
  filterRow.querySelectorAll('.filter-btn').forEach(btn=>btn.addEventListener('click',()=>{activeCategory=btn.dataset.category;filterRow.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderVideos();}));
  filterRow.querySelectorAll('.part-btn').forEach(btn=>btn.addEventListener('click',()=>{activePart=btn.dataset.part;filterRow.querySelectorAll('.part-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');renderVideos();}));
}
function renderVideos(){
 const selected=videos.filter(v=>(activeCategory==='All'||v.category===activeCategory)&&(activePart==='All Parts'||v.part===activePart));
 grid.innerHTML=selected.map(v=>`<article class="video-card ${v.featured?'video-featured':''}"><video controls preload="metadata" playsinline><source src="${v.file}" type="video/mp4">Your browser does not support MP4 playback.</video><div class="video-body"><div class="video-meta"><span>${v.category}</span><span>•</span><span>${v.part}</span>${v.featured?'<span class="featured-pill">Coach Pick</span>':''}</div><h3>${v.title}</h3><div class="analysis-block"><h4>What the sequence shows</h4><p>${v.sequence}</p></div><div class="analysis-block good"><h4>What the defenders did well</h4><p>${v.doneWell}</p></div><div class="analysis-block improve"><h4>What could be better / focus</h4><p>${v.improve}</p></div><div class="tip"><strong>Coaching cue:</strong> ${v.cue}</div></div></article>`).join('');
 document.getElementById('videoCount').textContent=`${selected.length} clips shown`;
}
renderFilters();renderVideos();
